<?php
/**
 * @file
 * Code for the Bamboo Slideshow feature.
 */

include_once 'bamboo_slideshow.features.inc';

/**
 * Implements hook_preprocess_views().
 *
 * Add custom js and css to specific views so it does not load globally.
 */
function bamboo_slideshow_preprocess_views_view(&$vars) {

  // Preprocess views.
  $view = $vars['view'];

  // Define the module path.
  $mod_path = drupal_get_path('module', 'bamboo_slideshow');

  // Add custom scripts for the the cards view.
  if ($view->name == 'bamboo_slideshow') {

    // Add theme CSS for slideshow.
    $bamboo_slideshow_css = array(
      '#attached' => array(
        'css' => array(
          $mod_path . '/css/bamboo-slideshow.css' => array(
            'group' => CSS_THEME,
            'weight' => 9999,
          ),
        ),
      ),
    );
    drupal_render($bamboo_slideshow_css);

  }

}
